/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje2;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JButton;

/**
 *
 * @author Batuhan Sevinç
 */
public class Anasayfa extends javax.swing.JFrame {
        public static  DLL dvdler=new DLL();
             
           
            /**
     * Creates new form NewJFrame
     */
    public Anasayfa() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DVD ENVANTER");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        Dvd_ekle = new javax.swing.JButton();
        Dvd_sil = new javax.swing.JButton();
        Bilgiler_goster = new javax.swing.JButton();
        cıkıs = new javax.swing.JButton();
        Secilensarkıcıdvdleri = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        Dvd_ekle.setBackground(new java.awt.Color(102, 204, 255));
        Dvd_ekle.setText("DVD Ekle");
        Dvd_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dvd_ekleActionPerformed(evt);
            }
        });

        Dvd_sil.setBackground(new java.awt.Color(102, 204, 255));
        Dvd_sil.setText("DVD Sil");
        Dvd_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dvd_silActionPerformed(evt);
            }
        });

        Bilgiler_goster.setBackground(new java.awt.Color(102, 204, 255));
        Bilgiler_goster.setText("Bilgileri Göster");
        Bilgiler_goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bilgiler_gosterActionPerformed(evt);
            }
        });

        cıkıs.setBackground(new java.awt.Color(102, 204, 255));
        cıkıs.setText("Çıkış");
        cıkıs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cıkısActionPerformed(evt);
            }
        });

        Secilensarkıcıdvdleri.setBackground(new java.awt.Color(102, 204, 255));
        Secilensarkıcıdvdleri.setText("DVD Bul");
        Secilensarkıcıdvdleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecilensarkıcıdvdleriActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("DVD ENVANTER UYGULAMASINA HOŞGELDİNİZ!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(cıkıs, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Secilensarkıcıdvdleri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Dvd_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Bilgiler_goster, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(Dvd_sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dvd_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bilgiler_goster, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Secilensarkıcıdvdleri, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dvd_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(cıkıs, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   
    private void Bilgiler_gosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bilgiler_gosterActionPerformed
       
        JFrameBilgiGoster frameRehber = new JFrameBilgiGoster();
        frameRehber.setVisible(true);
        
         
        
        
    }//GEN-LAST:event_Bilgiler_gosterActionPerformed

    private void cıkısActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cıkısActionPerformed
        JFrameYeniDVDEkle f=new JFrameYeniDVDEkle();
        Anasayfa d=new Anasayfa();
        DLL dl=new DLL();
        
        
            try
        {
            File silinecekDosya = new File("bilgiler.txt");

            // Dosyanin mevcut olup olmadigini kontrol et.
            if (!silinecekDosya.exists())
            throw new IllegalArgumentException("İlgili Dosya Bulunamadı! : "
            + silinecekDosya.getAbsolutePath());

            if (silinecekDosya.delete()) {
            System.out.println("Dosya Başarı İle Silindi.");
            }

            else {
            System.out.println("DOSYA Silme İşlemi Başarısız!");
            }

       }   catch (Exception e) {
           e.printStackTrace();
           }
     
    

        
        FileWriter fw = null;
         try {
                    File file = new File ("bilgiler.txt");
                    fw = new FileWriter(file);
                    try (BufferedWriter bfw = new BufferedWriter(fw)){
                        bfw.newLine();
                        bfw.write(d.dvdler.yazdırma2());
                    } catch (IOException ex) {
                        Logger.getLogger(JFrameYeniDVDEkle.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(JFrameYeniDVDEkle.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        fw.close();
                    } catch (IOException ex) {
                        Logger.getLogger(JFrameYeniDVDEkle.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
    
     System.exit(0);

        
    }//GEN-LAST:event_cıkısActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        
    }//GEN-LAST:event_formComponentHidden

    private void Dvd_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dvd_silActionPerformed
        JFrameSil frameSil = new JFrameSil();
        frameSil.setVisible(true);
    }//GEN-LAST:event_Dvd_silActionPerformed

    private void Dvd_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dvd_ekleActionPerformed
        JFrameYeniDVDEkle frameekle=new JFrameYeniDVDEkle();
        frameekle.setVisible(true);
    }//GEN-LAST:event_Dvd_ekleActionPerformed

    private void SecilensarkıcıdvdleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecilensarkıcıdvdleriActionPerformed
        adsoyadverilendvd adsoyad=new adsoyadverilendvd();
        adsoyad.setVisible(true);
         
    }//GEN-LAST:event_SecilensarkıcıdvdleriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FileNotFoundException {
        DLL sırlama=new DLL();
        String girdiKelime ; 
        String[] array2=null;
        String array[]=null;
        DVD d=new DVD();
         
        try{
           Scanner girdiOku = new Scanner(new FileReader("bilgiler.txt"));
                girdiKelime=girdiOku.nextLine();
                while (girdiOku.hasNextLine())
                {   
                    girdiKelime+=girdiOku.nextLine();
                    array=girdiKelime.split("\\.");
                }
                    for(String x:array){
                            array2=x.split(",");
                            dvdler.append(new DVD(array2[0].trim(), array2[1].trim(), Integer.valueOf(array2[2].trim()), Integer.valueOf(array2[3].trim())));
                            for(int i=4; i<array2.length; i++){
                                dvdler.sarkılar(array2[i].trim());
                            } 
              
            }

          } catch (IOException ex) {
            Logger.getLogger(Anasayfa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
       dvdler.quickSort(dvdler.head);
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anasayfa().setVisible(true);
                
            }
        });
       
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bilgiler_goster;
    private javax.swing.JButton Dvd_ekle;
    private javax.swing.JButton Dvd_sil;
    private javax.swing.JButton Secilensarkıcıdvdleri;
    private javax.swing.JButton cıkıs;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
