/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje2;


import javax.swing.JOptionPane;


public class JFrameSil extends javax.swing.JFrame {

    /**
     * Creates new form JFrameSil
     */
    public JFrameSil() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ENVANTERDEN SİL");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sanatcı = new javax.swing.JTextField();
        album_Adi = new javax.swing.JTextField();
        Envanterden_sil = new javax.swing.JButton();
        jButtonTemizle = new javax.swing.JButton();
        sanatcı_adı = new javax.swing.JLabel();
        albumadı = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REHBERDEN SİL");

        Envanterden_sil.setText("Envanterden Sil");
        Envanterden_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Envanterden_silActionPerformed(evt);
            }
        });

        jButtonTemizle.setText("Temizle");
        jButtonTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTemizleActionPerformed(evt);
            }
        });

        sanatcı_adı.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        sanatcı_adı.setText("Sanatçı");

        albumadı.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        albumadı.setText("Albüm Adı");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Sileceğiniz dvd bilgilerini giriniz.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(albumadı, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sanatcı_adı, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sanatcı, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(album_Adi)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(Envanterden_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jButtonTemizle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sanatcı_adı)
                    .addComponent(sanatcı, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(album_Adi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(albumadı))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Envanterden_sil)
                    .addComponent(jButtonTemizle))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTemizleActionPerformed
        sanatcı.setText("");
        album_Adi.setText("");
       
    }//GEN-LAST:event_jButtonTemizleActionPerformed

    private void Envanterden_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Envanterden_silActionPerformed
        DVD dvd=new DVD();
        DLL dl=new DLL();
        String isim=dvd.getAdSoyad();
        String albumadı=dvd.getDvdBaslık();
        String cıkıstarih=String.valueOf(dvd.getCıkısTarih());
        Anasayfa frame = new Anasayfa();
        DLL d=new DLL();
        isim = sanatcı.getText();
        albumadı = album_Adi.getText();
        
       
        int sil=Anasayfa.dvdler.selectdelete(sanatcı.getText().trim(), album_Adi.getText().trim());
        if ("".equals(isim) && "".equals(albumadı)) {
            JOptionPane.showMessageDialog(null, "Doldurulması Gereken Alanları Boş Bırakmayınız !", "Uyarı !", -1);
        }
        else if ("".equals(albumadı)) {
            JOptionPane.showMessageDialog(null, "Albüm adını Alanını Boş Bırakamazsınız!", "Uyarı !", -1);
        }
        else if ("".equals(isim)) {
            JOptionPane.showMessageDialog(null, "Sanatçı Adını Boş Bırakamazsınız!", "Uyarı !", -1);
        }

        else {
                if(sil==1){
                   frame.dvdler.selectdelete(isim,albumadı);
                   JOptionPane.showMessageDialog(null, "Silme İşlemi Başarıyla Gerçekleşti !","Uyarı !", -1); 
                }
                else 
                    JOptionPane.showMessageDialog(null, "Girdiğiniz bilgilerde bir DVD bulunmamaktadır...","Uyarı !", -1);
                }
                
       
        
    }//GEN-LAST:event_Envanterden_silActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameSil().setVisible(true);
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Envanterden_sil;
    private javax.swing.JTextField album_Adi;
    private javax.swing.JLabel albumadı;
    private javax.swing.JButton jButtonTemizle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField sanatcı;
    private javax.swing.JLabel sanatcı_adı;
    // End of variables declaration//GEN-END:variables
}
