/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje2;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class JFrameYeniDVDEkle extends javax.swing.JFrame {
    public static DVD dvd=new DVD();

    /**
     * Creates new form NewJFrame1
     */
    public JFrameYeniDVDEkle() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("YENİ DVD EKLE");
            }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        Sanatcıadı = new javax.swing.JTextField();
        AlbumAdı = new javax.swing.JTextField();
        AlbumCıkısTarihi = new javax.swing.JTextField();
        EnvantereEkle = new javax.swing.JButton();
        jButtonTemizle = new javax.swing.JButton();
        albumfiyatı = new javax.swing.JLabel();
        AlbumFiyati = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sarkılarr = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("YENİ KİŞİ EKLE");

        EnvantereEkle.setBackground(new java.awt.Color(102, 204, 255));
        EnvantereEkle.setText("Envantere Ekle");
        EnvantereEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnvantereEkleActionPerformed(evt);
            }
        });

        jButtonTemizle.setBackground(new java.awt.Color(255, 102, 102));
        jButtonTemizle.setText("Temizle");
        jButtonTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTemizleActionPerformed(evt);
            }
        });

        albumfiyatı.setText("Albüm Fiyatı");

        jLabel2.setText("Albümdeki Şarkılar");

        jLabel1.setText("Sanatçı Adı ve Soyadı");

        jLabel3.setText("Albüm Adı");

        jLabel4.setText("Albüm Çıkış Tarihi");

        sarkılarr.setColumns(20);
        sarkılarr.setRows(5);
        jScrollPane1.setViewportView(sarkılarr);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(EnvantereEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jButtonTemizle, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(albumfiyatı, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AlbumFiyati, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(Sanatcıadı)
                    .addComponent(AlbumAdı)
                    .addComponent(AlbumCıkısTarihi)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sanatcıadı, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlbumAdı, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlbumCıkısTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlbumFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(albumfiyatı))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTemizle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnvantereEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnvantereEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnvantereEkleActionPerformed
        File file = new File ("bilgiler.txt");
        
        FileWriter fw = null;
        
        DLL dl;
        String isim;
        String albumadı;
        String albumcıkıstarihi;
        String albumFiyatı;
        String albumdekisarkılar;

        isim = Sanatcıadı.getText();
        albumadı = AlbumAdı.getText();
        albumcıkıstarihi = AlbumCıkısTarihi.getText();
        albumFiyatı=AlbumFiyati.getText();
        albumdekisarkılar=sarkılarr.getText();
        
        if ("".equals(isim) && "".equals(albumadı)&& "".equals(albumcıkıstarihi)&& "".equals(albumFiyatı)&& "".equals(albumdekisarkılar)) {
            JOptionPane.showMessageDialog(null, "Doldurulması Gereken Alanları Boş Bırakmayınız !", "Uyarı !", -1); 
        }
        else if ("".equals(albumadı)) {
            JOptionPane.showMessageDialog(null, "Albüm Adı Alanını Boş Bırakamazsınız!", "Uyarı !", -1);
        } 
        else if ("".equals(isim)) {
            JOptionPane.showMessageDialog(null, "Sanatçının Adını ve Soyadını Boş Bırakamazsınız!", "Uyarı !", -1);
        }    
        else if ("".equals(albumcıkıstarihi)) {
            JOptionPane.showMessageDialog(null, "Albüm Çıkış Tarihi Alanını Boş Bırakamazsınız!", "Uyarı !", -1);
        }
        else if ("".equals(albumFiyatı)) {
            JOptionPane.showMessageDialog(null, "Albüm Fiyat Alanını Boş Bırakamazsınız!", "Uyarı !", -1);
        } 
        else if ("".equals(albumdekisarkılar)) {
            JOptionPane.showMessageDialog(null, "Albümdeki  Şarkılar Alanını Boş Bırakamazsınız!", "Uyarı !", -1);
        } 
        
        else {

         
          DLL dll=new DLL();
          ArrayList<String> sarkılar=new ArrayList<String>();
          Anasayfa f=new Anasayfa();
          
          dvd=new DVD( isim,albumadı,Integer.parseInt(albumcıkıstarihi),Integer.parseInt(albumFiyatı),sarkılar);
          f.dvdler.append(dvd);
            String[] sarkilar=sarkılarr.getText().split(",");
             for (String song : sarkilar) {
                f.dvdler.sarkılar(song);
            }
          
            JOptionPane.showMessageDialog(null, "Yeni DVD Envantere Eklenmiştir.", "Bilgi", -1);
        }
        JFrameYeniDVDEkle f=new JFrameYeniDVDEkle();
        Anasayfa d=new Anasayfa();
        String Yazılacak=d.dvdler.yazdırma2();

     
    }//GEN-LAST:event_EnvantereEkleActionPerformed

    private void jButtonTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTemizleActionPerformed
        Sanatcıadı.setText("");
        AlbumAdı.setText("");
        AlbumCıkısTarihi.setText("");
        AlbumFiyati.setText("");
        sarkılarr.setText("");
    }//GEN-LAST:event_jButtonTemizleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameYeniDVDEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameYeniDVDEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameYeniDVDEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameYeniDVDEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameYeniDVDEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlbumAdı;
    private javax.swing.JTextField AlbumCıkısTarihi;
    private javax.swing.JTextField AlbumFiyati;
    private javax.swing.JButton EnvantereEkle;
    private javax.swing.JTextField Sanatcıadı;
    private javax.swing.JLabel albumfiyatı;
    private javax.swing.JButton jButtonTemizle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea sarkılarr;
    // End of variables declaration//GEN-END:variables
}
